# Automatically created bt "no-headache-django" project.
# Star me on github http://github.com/mrsaemir/no-headache-django

version: '3'

services:
  web:
    restart: always
    build: .
    ports:
      - 8000:8000
    networks:
      project_network:
    depends_on:
      - db
    volumes:
      - ./:/home/user/project_core
      - ../development_data_7CXpFi/static:/home/user/static/
      - ../development_data_7CXpFi/media:/home/user/media/

    command: bash -c "python manage.py makemigrations && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"

    env_file:
      - vars.env

  db:
    restart: always
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_USER=some_user
      - POSTGRES_PASSWORD=some_password
      - POSTGRES_DB=some_db
    networks:
      project_network:
    volumes:
      - ../development_data_7CXpFi/postgres:/var/lib/postgresql/data

networks:
  project_network:
